name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Get Binary Version
      run: .\Get-ReleaseVersion.ps1 >> $env:NEWVERSION
    - name: Persist NEWVERSION
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
      uses: nick-invision/persist-action-data@v1
      with:
        data: ${{ env.NEWVERSION }}
        variable: NEWVERSION
